version: '3'
services:
  graphql_redis:
    restart: always
    image: "redis"
    ports:
        - "63000:6379"
  graphql_postgres:
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=graphql
    image: "mdillon/postgis"
    ports:
        - "63001:5432"
  graphql:
    build: .
    depends_on:
      - graphql_postgres
      - graphql_redis
    links:
      - graphql_postgres
      - graphql_redis
    ports: 
      - 63002:9000
    environment:
      REACT_APP_API_ROOT: http://localhost:63002
      REACT_APP_REDUX_LOGGING_ENABLED: "true"
      API_SECRET: shhhh
      DATABASE_URL: postgres://postgres:password@graphql_postgres:5432/graphql
      REDIS_URL: redis://graphql_redis:6379
      REDIS_USER_SESSIONS_DB: 1
      RECREATE_SCHEMA: "true"
    command: ["./wait-for-it.sh", "graphql_postgres:5432", "--", "npm", "start"]